multipartParser:
  maxMem: 134217728
s3:
  endpoint: minio:9000
  accessKeyID: test-access-key
  secretAccessKey: test-secret-key
  useSSL: false
  bucketName: senketsu-test
redis:
  address: redis:6379
  prefix: senketsu
