version: '3'
services:
  senketsu:
    build: .
    depends_on:
      - minio
      - redis
    ports:
      - 8080:8080

  senketsu-dev:
    image: cosmtrek/air:v1.15.1
    depends_on:
      - minio
      - redis
    working_dir: "/senketsu"
    environment:
      air_wd: "/senketsu"
    volumes:
      - .:/senketsu
    ports:
      - 8080:8080
    command: air -c .air.toml

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: test-access-key
      MINIO_SECRET_KEY: test-secret-key
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
    command: ["server", "/data"]

  redis:
    image: redis:latest
    ports:
      - 6379:6379


volumes:
  minio-data:
